apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cicd-demo
    app.kubernetes.io/instance: cicd-demo-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: mgma-pqla-cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgma-pqla-cicd
  template:
    metadata:
      labels:
        app: mgma-pqla-cicd
    spec:
      containers:
        - image: 211711023937.dkr.ecr.us-east-2.amazonaws.com/dp003:latest
          imagePullPolicy: Always
          name: mgma-pqla-cicd
          ports:
            - containerPort: 3000
