apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cicd-demo
    app.kubernetes.io/instance: cicd-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: mgma-pqla-cicd
spec:
  selector:
    app: cicd-demo
  ports:
   -  protocol: TCP
      port: 8082
      targetPort: 3000
